//! T2.b — real evidence-at-rest encryption.
//!
//! V0_GROUND_TRUTH.md §6.3 flagged the original `encrypt_evidence` (XOR with a
//! constant-string key, mislabelled "AES-256-GCM") as not cryptographic. T0.c
//! renamed it to `obfuscate_evidence` so the name no longer lies. T2.b adds a
//! REAL AES-256-GCM implementation alongside, keyed by an operator-supplied
//! 32-byte secret loaded from the `BALONCORE_EVIDENCE_KEY` env var (base64'd).
//!
//! Design:
//! - The plaintext is encrypted with AES-256-GCM. A fresh 12-byte nonce is
//!   generated by the OS RNG for every call (NIST SP 800-38D requires nonces
//!   never to repeat under the same key).
//! - The on-disk envelope is `nonce || ciphertext_with_tag`. The 16-byte GCM
//!   tag is appended to ciphertext by the `aes-gcm` crate.
//! - Decryption verifies the tag; if a single byte of ciphertext, nonce, or
//!   tag is flipped the call returns an error and NO plaintext is produced.
//!
//! Key sources:
//! - `EncryptionKey::from_env("BALONCORE_EVIDENCE_KEY")` — expects a base64-
//!   encoded 32-byte secret. Anything else is an error.
//! - `EncryptionKey::generate()` — OS RNG; for tests only.
//!
//! What this does NOT do (NEEDS-HUMAN):
//! - No KMS provider trait. Each operator currently manages the key themselves
//!   via env. A real KMS integration (AWS KMS, GCP KMS, HashiCorp Vault) is
//!   the next step.
//! - No per-tenant / per-bundle key wrapping. Today the same 32-byte master
//!   key encrypts every bundle. Envelope encryption (per-bundle DEK wrapped
//!   by KEK) is the next refinement.
//! - The `obfuscate_evidence` XOR function is left in place but marked
//!   `#[deprecated]` so the migration is visible to callers and tests.

use aes_gcm::aead::{Aead, KeyInit, OsRng};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use rand::RngCore;
use thiserror::Error;

/// 32-byte AES-256-GCM key. Construct via `from_env` or `generate` only.
/// Equality/Debug deliberately do NOT expose the secret material.
#[derive(Clone)]
pub struct EncryptionKey {
    bytes: [u8; 32],
}

impl std::fmt::Debug for EncryptionKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "EncryptionKey(<32 bytes, redacted>)")
    }
}

impl EncryptionKey {
    /// Load a 32-byte AES-256-GCM key from the named environment variable.
    /// The env value must be base64-encoded (standard alphabet, padded) and
    /// decode to exactly 32 bytes.
    pub fn from_env(var_name: &str) -> Result<Self, EncryptionError> {
        let raw = std::env::var(var_name).map_err(|_| {
            EncryptionError::MissingKey(format!("environment variable {var_name} not set"))
        })?;
        let decoded = B64
            .decode(raw.trim().as_bytes())
            .map_err(|e| EncryptionError::InvalidKey(format!("base64 decode: {e}")))?;
        if decoded.len() != 32 {
            return Err(EncryptionError::InvalidKey(format!(
                "expected 32 decoded bytes, got {}",
                decoded.len()
            )));
        }
        let mut bytes = [0u8; 32];
        bytes.copy_from_slice(&decoded);
        Ok(Self { bytes })
    }

    /// Generate a fresh random key. **For tests only** — production keys
    /// must come from a real KMS or operator-managed secret store.
    pub fn generate() -> Self {
        let mut bytes = [0u8; 32];
        OsRng.fill_bytes(&mut bytes);
        Self { bytes }
    }

    /// Render the key as a base64 string suitable for `BALONCORE_EVIDENCE_KEY`.
    /// Use sparingly; never log the result.
    pub fn to_base64(&self) -> String {
        B64.encode(self.bytes)
    }

    fn aead(&self) -> Aes256Gcm {
        Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(&self.bytes))
    }
}

#[derive(Debug, Error)]
pub enum EncryptionError {
    #[error("missing key: {0}")]
    MissingKey(String),
    #[error("invalid key: {0}")]
    InvalidKey(String),
    #[error("AES-GCM seal failed (unexpected; this typically indicates a bug)")]
    SealFailed,
    #[error("AES-GCM open failed: ciphertext authentication failed (tampered or wrong key)")]
    AuthFailed,
    #[error("malformed envelope: {0}")]
    Malformed(String),
}

/// Encrypt `plaintext` with AES-256-GCM under `key`. The returned envelope is
/// `nonce || ciphertext || tag` (28-byte overhead beyond plaintext length).
pub fn encrypt_evidence_aes_gcm(
    plaintext: &[u8],
    key: &EncryptionKey,
) -> Result<Vec<u8>, EncryptionError> {
    let mut nonce_bytes = [0u8; 12];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);
    let aead = key.aead();
    let ciphertext = aead
        .encrypt(nonce, plaintext)
        .map_err(|_| EncryptionError::SealFailed)?;
    let mut envelope = Vec::with_capacity(12 + ciphertext.len());
    envelope.extend_from_slice(&nonce_bytes);
    envelope.extend_from_slice(&ciphertext);
    Ok(envelope)
}

/// Decrypt a `nonce || ciphertext || tag` envelope. Fails if the envelope is
/// too short, the tag doesn't verify, or the key is wrong.
pub fn decrypt_evidence_aes_gcm(
    envelope: &[u8],
    key: &EncryptionKey,
) -> Result<Vec<u8>, EncryptionError> {
    if envelope.len() < 12 + 16 {
        return Err(EncryptionError::Malformed(format!(
            "envelope too short: {} bytes (need >= 28)",
            envelope.len()
        )));
    }
    let (nonce_bytes, ciphertext) = envelope.split_at(12);
    let nonce = Nonce::from_slice(nonce_bytes);
    let aead = key.aead();
    aead.decrypt(nonce, ciphertext)
        .map_err(|_| EncryptionError::AuthFailed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_recovers_plaintext() {
        let key = EncryptionKey::generate();
        let plaintext = b"verified BOLA at /api/orgs/org-b/projects/proj-b-001";
        let ct = encrypt_evidence_aes_gcm(plaintext, &key).expect("seal");
        let pt = decrypt_evidence_aes_gcm(&ct, &key).expect("open");
        assert_eq!(pt.as_slice(), plaintext);
    }

    #[test]
    fn different_key_cannot_decrypt() {
        let k1 = EncryptionKey::generate();
        let k2 = EncryptionKey::generate();
        let ct = encrypt_evidence_aes_gcm(b"secret", &k1).expect("seal");
        let err = decrypt_evidence_aes_gcm(&ct, &k2).unwrap_err();
        match err {
            EncryptionError::AuthFailed => {}
            other => panic!("expected AuthFailed for wrong key, got {other:?}"),
        }
    }

    #[test]
    fn tamper_detection_single_byte_flip() {
        let key = EncryptionKey::generate();
        let plaintext = b"original evidence body";
        let mut ct = encrypt_evidence_aes_gcm(plaintext, &key).expect("seal");
        // Flip a byte in the ciphertext region (after the 12-byte nonce).
        let idx = 12 + 4;
        ct[idx] ^= 0x01;
        let err = decrypt_evidence_aes_gcm(&ct, &key).unwrap_err();
        match err {
            EncryptionError::AuthFailed => {}
            other => panic!("expected AuthFailed for tampered ciphertext, got {other:?}"),
        }
    }

    #[test]
    fn tamper_detection_nonce_flip() {
        let key = EncryptionKey::generate();
        let mut ct = encrypt_evidence_aes_gcm(b"x", &key).expect("seal");
        ct[0] ^= 0x80;
        let err = decrypt_evidence_aes_gcm(&ct, &key).unwrap_err();
        assert!(matches!(err, EncryptionError::AuthFailed));
    }

    #[test]
    fn from_env_missing_returns_missing_key() {
        std::env::remove_var("BALONCORE_TEST_AESGCM_KEY_MISSING_PROBE");
        let err = EncryptionKey::from_env("BALONCORE_TEST_AESGCM_KEY_MISSING_PROBE").unwrap_err();
        assert!(matches!(err, EncryptionError::MissingKey(_)));
    }

    #[test]
    fn from_env_wrong_length_returns_invalid_key() {
        let var = "BALONCORE_TEST_AESGCM_KEY_SHORT";
        // 16 bytes base64'd — wrong length.
        std::env::set_var(var, B64.encode([0u8; 16]));
        let err = EncryptionKey::from_env(var).unwrap_err();
        std::env::remove_var(var);
        match err {
            EncryptionError::InvalidKey(msg) => {
                assert!(msg.contains("32"), "msg: {msg}");
            }
            other => panic!("expected InvalidKey, got {other:?}"),
        }
    }

    #[test]
    fn from_env_round_trip() {
        let var = "BALONCORE_TEST_AESGCM_KEY_RT";
        let key = EncryptionKey::generate();
        std::env::set_var(var, key.to_base64());
        let loaded = EncryptionKey::from_env(var).unwrap();
        std::env::remove_var(var);
        let plaintext = b"round trip";
        let ct = encrypt_evidence_aes_gcm(plaintext, &key).expect("seal");
        let pt = decrypt_evidence_aes_gcm(&ct, &loaded).expect("open with loaded key");
        assert_eq!(pt.as_slice(), plaintext);
    }

    #[test]
    fn envelope_overhead_is_28_bytes() {
        let key = EncryptionKey::generate();
        let ct_empty = encrypt_evidence_aes_gcm(b"", &key).expect("seal");
        // 12 (nonce) + 0 (plaintext) + 16 (tag) = 28.
        assert_eq!(ct_empty.len(), 28);
        let ct_one = encrypt_evidence_aes_gcm(b"a", &key).expect("seal");
        assert_eq!(ct_one.len(), 29);
    }

    #[test]
    fn ciphertext_changes_per_call_for_same_plaintext() {
        // Pin: nonces must not repeat — two seals of the same plaintext
        // must produce different envelopes.
        let key = EncryptionKey::generate();
        let a = encrypt_evidence_aes_gcm(b"same", &key).expect("seal a");
        let b = encrypt_evidence_aes_gcm(b"same", &key).expect("seal b");
        assert_ne!(a, b, "fresh nonce must produce different envelopes");
    }

    #[test]
    fn malformed_envelope_returns_malformed() {
        let key = EncryptionKey::generate();
        let err = decrypt_evidence_aes_gcm(&[0u8; 10], &key).unwrap_err();
        assert!(matches!(err, EncryptionError::Malformed(_)));
    }

    #[test]
    fn debug_does_not_leak_key_material() {
        let key = EncryptionKey::generate();
        let dbg = format!("{:?}", key);
        assert!(dbg.contains("redacted"), "Debug must redact, got: {dbg}");
        // Sanity: the base64'd key should not appear in Debug output.
        let b64 = key.to_base64();
        assert!(!dbg.contains(&b64));
    }
}
